version: '3'

services:
  testproject:
    build: .
    command: python3 testproject/manage.py test cc
    # command: python3 testproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - dashd
      - bitcoind
      - litecoind
      - zcashd

  bitcoind:
    image: btcpayserver/bitcoin:0.17.0
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |-
        rpcuser=root
        rpcpassword=toor
        rpcport=43782
    ports:
      - "43782:43782"

  dashd:
    image: btcpayserver/dash:0.13.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        regtest=1
        rpcuser=root
        rpcpassword=toor
        rpcport=19998
    ports:
      - "19998:19998"

  litecoind:
    image: nicolasdorier/docker-litecoin:0.16.3
    environment:
      BITCOIN_EXTRA_ARGS: |-
        regtest=1
        rpcuser=root
        rpcpassword=toor
        rpcport=19335
    ports:
      - "19335:19335"

  zcashd:
    image: messari/zcash-core:2.0.3
    command: -printtoconsole -regtest=1 -rpcuser=root -rpcpassword=toor -server -rest -rpcallowip=0.0.0.0/0
    ports:
      - "18232:18232"
